### ISSUE TITLE
Video recording finish on iPhone does not work

### ISSUE THREAD

**Issue by felipehv** [Ziggeo/react-ziggeo#75]
# Device
* iPhone
* Safari (because embedded recorder does not work on Chrome)
* Using iPhone simulator on Google Chrome for Mac for getting console logs.

# Bug description

We developed our custom Stop button, using the `recorder.stop()` function (recorder is a reference to the ZiggeoRecorder.

When pressing the button, after around 2 or 3 seconds, the timer continues and the console shows the following exception

![image](https://user-images.githubusercontent.com/11399594/96589712-86854f80-12bb-11eb-8f0f-7a998a595b4f.png)

This problem also happens when letting the video recording finish (after `timelimit` seconds, i.e. 30 seconds), without using `stop()`. Same exception message is shown.

**Comment by Bane-D** [comment]
Hey Felipe,

Thank you for the layout of the info. Can you tell me what version of our Ziggeo library you are using?

By library I am checking mostly for https://github.com/Ziggeo/react-ziggeo/blob/master/package.json#L76 and if it is 2.35.22, or some other version?

Also since you mention that it happens for both clicking and when it stops automatically are you maybe listening to the events such as the one for stopped recording or about uploads?

**Comment by felipehv** [comment]
Hi Bane, thanks for answering.

About the library `ziggeo-client-sdk` we are currently using 2.36.5, with `react-ziggeo` 4.3.3.

Yes, it happens both clicking the button, that triggers `recorder.stop()` and when the countdown goes to 0.

This is our event listening for countdown and time progress.

![image](https://user-images.githubusercontent.com/11399594/96773074-68524900-13ba-11eb-8dd9-15bece2bd9db.png)

We also use `onProcessed` and `onUploading` and some other callbacks (with state changes only).

![image](https://user-images.githubusercontent.com/11399594/96773324-bbc49700-13ba-11eb-96c5-55e8673d23a1.png)

**Comment by felipehv** [comment]
Just downgraded ziggeo SDK to 2.35.22 and same problem happens, but with more info in logs.

![image](https://user-images.githubusercontent.com/11399594/96775021-46a69100-13bd-11eb-8a0c-48043e7d67e7.png)

**Comment by Bane-D** [comment]
Thank you Felipe.

Personally I would suggest checking the times with ranges so instead of `time === 0` to be something like `time <= 0` instead.

Since we did not get anyone else reporting this and you are using the latest revision of our Javascript library then I am thinking it might be good to comment out the onUploading and onUploaded handler just to make sure nothing within the same is doing this.

My colleague has checked with the standard codes and it was working fine for him. That is possible either due to the way some parameters are set or something with the events. If you are fine with sharing those details here, please feel free to. If not fine to send us an email to support@ziggeo.com instead, with that info (the recorder code) and we can continue here so others benefit if they have the same setup.

**Comment by felipehv** [comment]
Trying again on iPhone this time (not Google Chrome simulated iPhone) it worked, with some design issues but it finally recorded. The range helped with this issues I guess.

But on the other hand, when the recorder is on `demo=true` mode, when I finish recording, the video player does not work and shows this message.

![image](https://user-images.githubusercontent.com/11399594/97050868-805dd000-1554-11eb-9479-aba140055aaf.png)

Also when the 3,2,1 countdown goes to 0, its has like a 2 second delay, when the video recorder does not record.

Thanks for helping!

**Comment by Bane-D** [comment]
Hi Felipe,

Glad to hear that you are no longer getting an issue and that the time range helped :)

I am not entirely sure what you mean by `demo=true` I can only presume that it is our `simulate` parameter, however not really sure.

It does seem like it is a different issue, or likely more of a support question (support@ziggeo.com). Our team can then help you with any questions about our system :)

In terms of the delay, that is possible. Our code makes a call to the browser API to start recording. For various reasons such as system resources or the camera availability the browser might need to have a delay however our code does not add any delay of its own. So as soon as there is a 0 it will make a call to start the recording. :)

**Comment by felipehv** [comment]
Hi Bane, yes sorry, is the `simulate` parameter, I am using a prop called `demo` so I got confused.

About the delay, the countdown goes to zero and it does not start until 2 or 3 more seconds, while the loader animation is still on screen, but without any numbers.

Thanks again for all the help

[UPDATE]
The problem with the `simulate=true` parameter also happens on MacOS 10.15.7 on Safari. I cannot play the recorded video for a preview.

**Comment by felipehv** [comment]
Hi @Bane-D , any news on this issue? Thanks in advance!

**Comment by sambua** [comment]
Hello @felipehv could you please upgrade to the latest version `Ziggeo Client SDK 2.36.10` and test again? Console error you reported here should be fixed https://github.com/Ziggeo/react-ziggeo/issues/75#issuecomment-713834595; 

Regarding delay after countdown it's related connection to the to the stream server. So it's not manageable by us, it could be related to the internet speed and 3rd party server respond which we are using. Countdown purpose mostly it make user be prepared before recorder actually starts. Will look how could make it more UX friendly, maybe hold on 0 while server connection is fully ready. If you have any advice will be glad to hear, tanks in advance.

**Comment by felipehv** [comment]
Thanks @sambua , I changed the version of ziggeo sdk but problem is still there. Maybe it should be updated on react-ziggeo package.json too? Also I think it is related to the issue that I explain below.

More important than the delay between 0 and start recording, is the issue from https://github.com/Ziggeo/react-ziggeo/issues/75#issuecomment-715576528 , where the `simulate=true` mode does not work when the recording is finished and the user wants to watch its recording.
Here is another image of what happens (mostly on Safari). It is very important for us that our users can make sure they can record both audio and video well.

![image](https://user-images.githubusercontent.com/11399594/97992987-3f6e8280-1dc2-11eb-8e91-eb0902e927de.png)


Thanks for your time!
Felipe.

**Comment by sambua** [comment]
Thanks @felipehv , did you still get the same error message showing size related error ? Could you please on your console also type `ZiggeoApi.V2.Device.info.revision` It should give you SDK version you're using. 

Just in case to be able upgrade SDK version you need, change package.json Ziggeo version and run `build` command. 

P.S: we have to leave stable version, so why we are not upgrade it to the lates version.
